# OpenFisca -- A versatile microsimulation software
# By: OpenFisca Team <contact@openfisca.fr>
#
# Copyright (C) 2011, 2012, 2013, 2014, 2015 OpenFisca Team
# https://github.com/openfisca
#
# This file is part of OpenFisca.
#
# OpenFisca is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# OpenFisca is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Generated by openfisca-parsers script "./openfisca_parsers/scripts/decomposition_to_julia.py"
# From XML decomposition "decomp.xml" in "openfisca_france"
# WARNING: Any manual modification may be lost.


const DECOMPOSITION = @decomposition_node revdisp [
    @decomposition_node rev_net [
        @decomposition_node rev_trav [
            @decomposition_node salnet [
                @decomposition_node sal [
                    @decomposition_node salbrut [
                        @decomposition_node salsuperbrut []
                        @decomposition_node cotisations_patronales []
                        @decomposition_node allegement_fillon []
                        @decomposition_node credit_impot_competitivite_emploi []
                        @decomposition_node tehr []
                    ]
                    @decomposition_node cotisations_salariales []
                    @decomposition_node csgsald []
                    @decomposition_node mhsup []
                ]
                @decomposition_node csgsali []
                @decomposition_node crdssal []
                @decomposition_node forfait_social []
                @decomposition_node hsup []
            ]
            @decomposition_node rag []
            @decomposition_node ric []
            @decomposition_node rnc []
        ]
        @decomposition_node pen [
            @decomposition_node chonet [
                @decomposition_node cho [
                    @decomposition_node chobrut []
                    @decomposition_node csgchod []
                ]
                @decomposition_node csgchoi []
                @decomposition_node crdscho []
            ]
            @decomposition_node rstnet [
                @decomposition_node rst [
                    @decomposition_node rstbrut []
                    @decomposition_node csgrstd []
                ]
                @decomposition_node csgrsti []
                @decomposition_node crdsrst []
            ]
            @decomposition_node alr []
            @decomposition_node alv []
            @decomposition_node rto []
        ]
        @decomposition_node rev_cap_net [
            @decomposition_node rev_cap_brut [
                @decomposition_node fon []
                @decomposition_node f3vg []
                @decomposition_node f3vz []
                @decomposition_node rev_cap_bar []
                @decomposition_node rev_cap_lib []
                @decomposition_node rac []
            ]
            @decomposition_node cotsoc_cap [
                @decomposition_node prelsoc_cap [
                    @decomposition_node prelsoc_fon []
                    @decomposition_node prelsoc_pv_mo []
                    @decomposition_node prelsoc_pv_immo []
                    @decomposition_node prelsoc_cap_bar []
                    @decomposition_node prelsoc_cap_lib []
                ]
                @decomposition_node csg_cap [
                    @decomposition_node csg_fon []
                    @decomposition_node csg_pv_mo []
                    @decomposition_node csg_pv_immo []
                    @decomposition_node csg_cap_bar []
                    @decomposition_node csg_cap_lib []
                ]
                @decomposition_node crds_cap [
                    @decomposition_node crds_fon []
                    @decomposition_node crds_pv_mo []
                    @decomposition_node crds_pv_immo []
                    @decomposition_node crds_cap_bar []
                    @decomposition_node crds_cap_lib []
                ]
            ]
            @decomposition_node imp_lib []
        ]
    ]
    @decomposition_node psoc [
        @decomposition_node pfam [
            @decomposition_node af []
            @decomposition_node cf []
            @decomposition_node ars []
            @decomposition_node aeeh []
            @decomposition_node paje [
                @decomposition_node paje_base []
                @decomposition_node paje_nais []
                @decomposition_node paje_clca []
                @decomposition_node paje_colca []
                @decomposition_node paje_clmg []
            ]
            @decomposition_node asf []
            @decomposition_node crds_pfam []
        ]
        @decomposition_node mini [
            @decomposition_node aspa []
            @decomposition_node aah []
            @decomposition_node caah []
            @decomposition_node asi []
            @decomposition_node rsa []
            @decomposition_node psa []
            @decomposition_node aefa []
            @decomposition_node api []
        ]
        @decomposition_node aides_logement [
            @decomposition_node apl []
            @decomposition_node als []
            @decomposition_node alf []
            @decomposition_node alset []
            @decomposition_node crds_logement []
        ]
    ]
    @decomposition_node ppe []
    @decomposition_node impo [
        @decomposition_node irpp []
        @decomposition_node ir_pv_immo []
        @decomposition_node isf_net [
            @decomposition_node isf_tot []
            @decomposition_node bouclier_fiscal []
        ]
        @decomposition_node taxe_habitation []
    ]
]
